usasearch.settings:
  type: mapping
  label: 'DigitalGov Search Module Settings'
  mapping:
    affiliate_name:
      type: string
      label: 'Affilate Name'
    autocomplete:
      type: boolean
      label: 'Enable autocomplete'
    action_domain:
      type: string
      label: 'Search domain'
    description_view_mode:
      type: string
      label: 'Description View Mode'
    action_endpoint:
      type: string
      label: 'Search endpoint'
    i14y_enabled:
      type: boolean
      label: 'Enable i14y API'
    drawer_handle:
      type: string
      label: 'Drawer Handle'
    secret_token:
      type: string
      label: 'i14y API Secret Token'
